### ISSUE TITLE
[$600] Update theme for mobile views

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums-theme#8]
This ticket will track updating the Topcoder Vanilla theme for mobile

* Zeplin: https://app.zeplin.io/project/5eabb382c71a001b66ff9b51
* MarvelApp:  https://marvelapp.com/afcedbb

This will include the header and footer.

The burger menu should match the menu from the Topcoder site:

![Screen Shot 2020-05-06 at 11 02 30](https://user-images.githubusercontent.com/21790/81129859-155e1400-8f89-11ea-9008-fd756e0b3075.png)

**Comment by lakshmiathreya** [comment]
@sdgun @jmgasper - seems like this was released as part of Forums Theme 1.8.2 release. Please note these process items: 
1. We need to move this to milestone Forums Theme 1.8.2. 
2. Also, do reference the relevant Forums Issue for this fix. 
3. Pls add current QA status for this Issue. 
Thanks! 

Requesting access to this Repo for @sathyajayabal and me as well.

**Comment by jmgasper** [comment]
@lakshmiathreya - I'm not sure where you're seeing that.  This issue was completed over a year ago, as part of the initial work we did on the forums.  It wasn't tied to a milestone as this was part of the initial release and work.
